### ISSUE TITLE
how can I assign the value of guid in newrelic.synthetics.ScriptMonitor to a static variable?

### ISSUE THREAD

**Issue by fsdrw08** [pulumi/pulumi-newrelic#817]
### Describe what happened

I need to refer newrelic.synthetics.ScriptMonitor's guid, then render this guid into a list of nrqlAlertConditions nrql query
my config:
```yaml
config:
  nrCertMonitoring:nrqlAlertConditions:
    # daysNearlyExpiration (1)
    - required:
        name: SRE_Monitor_Certificates-alert_condition_expiring_1-prod
        nrql:
          query: SELECT latest(custom.nearlyExpiringCertsLength) FROM SyntheticCheck WHERE entityGuid = '{}'
        # warning:
        critical:
          threshold: 1
          operator: above_or_equals
          threshold_duration: 60
          threshold_occurrences: AT_LEAST_ONCE
      optional:
        type: static
        enabled: true
    # daysBeforeExpiration (30)
    - required:
        name: SRE_Monitor_Certificates-alert_condition_expiring_2-prod
        nrql:
          query: SELECT latest(custom.expiringCertsLength) FROM SyntheticCheck WHERE entityGuid = '{}'
        warning:
          threshold: 1
          operator: above_or_equals
          threshold_duration: 60
          threshold_occurrences: AT_LEAST_ONCE
        # critical:
      optional:
        type: static
        enabled: true
```
I need to update this config by below code
```python
# update nrql alert condition's query, put script monitor id into the query
nrql_alert_conditions_config = config.require_object("nrqlAlertConditions")
nrql_alert_conditions_config_updated = []
for nrqlAlertCondition in nrql_alert_conditions_config:
    nrqlAlertCondition_updated = nrqlAlertCondition.copy()
    query: str = str(nrqlAlertCondition["required"]["nrql"]["query"])
    # in order to put script monitor guid into the query, we have to use below method to present the query string
    nrqlAlertCondition_updated["required"]["nrql"]["query"] = script_monitor.guid.apply(lambda guid: query.format(guid))

    nrql_alert_conditions_config_updated.append(nrqlAlertCondition_updated)
```

It doesnt work because the variable assigned to nrqlAlertCondition_updated["required"]["nrql"]["query"]  is a async object, it makes the result of the query will be the same one.

Now I would like to set the guid in newrelic.synthetics.ScriptMonitor to a static variable, how?

### Sample program

see above

### Output of `pulumi about`

```
CLI
Version      3.122.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME      VERSION
resource  newrelic  5.25.3
language  python    unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in python: executable='C:\Users\xxx\AppData\Local\pypoetry\Cache\virtualenvs\sre-iac-6JBwHF1h-py3.11\Scripts\python.exe' version='3.11.9'

Backend
Name           DESKTOP-IN2K25I
URL            azblob://pulumistate/nrcertmonitoring
User           AzureAD\xxx
Organizations
Token type     personal

Dependencies:
NAME                  VERSION
black                 23.12.1
flakehell             0.9.0
pip                   23.3.1
pulumi_newrelic       5.25.3
pytest                7.4.2
requests              2.29.0
serko-product-config  1.6.10
yamllint              1.32.0

Pulumi locates its logs in C:\Users\xxx\AppData\Local\Temp by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @fsdrw08 Can you show me an example of what you are trying to accomplish? It's not possible to go from an `Output[T]` to a `T`, but I take a look at what your doing and see if I can provide a working solution.

**Comment by fsdrw08** [comment]
Here is the pulumi arg config
```yaml
config:
  nrCertMonitoring:scriptMonitor:
    name: SRE_Monitor_Certificates
    status: ENABLED
    locations_publics:
      - AWS_AP_SOUTHEAST_2
    period: EVERY_DAY
    type: SCRIPT_API
    runtime_type: NODE_API
    runtime_type_version: "16.10"
    script_language: JAVASCRIPT
  nrCertMonitoring:nrqlAlertConditions:
    # daysNearlyExpiration (1)
    - required:
        name: SRE_Monitor_Certificates-alert_condition_expiring_1-prod
        nrql:
          # need to render the script monitor's guid into query, 
          query: SELECT latest(custom.nearlyExpiringCertsLength) FROM SyntheticCheck WHERE entityGuid = '{}'
        # warning:
        critical:
          threshold: 1
          operator: above_or_equals
          threshold_duration: 60
          threshold_occurrences: AT_LEAST_ONCE
      optional:
        type: static
        enabled: true
    # daysBeforeExpiration (30)
    - required:
        name: SRE_Monitor_Certificates-alert_condition_expiring_2-prod
        nrql:
          query: SELECT latest(custom.expiringCertsLength) FROM SyntheticCheck WHERE entityGuid = '{}'
        warning:
          threshold: 1
          operator: above_or_equals
          threshold_duration: 60
          threshold_occurrences: AT_LEAST_ONCE
        # critical:
      optional:
        type: static
        enabled: true
```

We need to create `newrelic.synthetics.ScriptMonitor`, then get ScriptMonitor's guid, render the guid into the list object's attribute `config.nrqlAlertConditions[*].required.nrql`, then pass the rendered arg into `newrelic.NrqlAlertCondition`
